Fix #8 General Localization - README
mozillascience/studyGroup pull request #73
Opened 2017-03-23 08:21 UTC by AnamikaD

@auremoser The README-ch.md is in Chinese Language. Please review it!

2017-03-23 14:12 UTC, auremoser requested changes
Thanks so much for this, it's awesome, I asked for one file to be removed and minor changes.

2017-03-23 14:12 UTC, auremoser commented on README-ch.md
> +什么做的研究组在实际生活吗? 检查了波士顿大学的研究组的网站和大学的 Tornonto 编码器的网站。 您也可以观看几个短的视频从研究组的领导在我们的方向指南。
This should be Toronto (like the city in Canada), I updated the english readme with correct spelling too!

2017-03-23 14:12 UTC, auremoser commented on _config.yml
>  calendar_embed_url: "https://www.google.com/calendar/embed?src=USER@gmail.com"
Would you mind removing this file from your pull request? I think you mean to updated your own calendar on your fork, and not the calendar from the studyGroup base repo. Unfortunately, when you submit a pull request, it chains subsequent commits to that PR until your PR is merged. Sorry!

2017-03-23 14:12 UTC, auremoser commented on README-ch.md
> +# Mozilla 研究组
This is so cool. I don't speak chinese so I can't verify the content, do you have a friend who can proofread and give a 👍 ?

2017-03-23 16:58 UTC, AnamikaD commented
@auremoser Thank you for the review! Review for Chinese language is difficult! Hindi is a second largest language spoken by Indians! So, I have made the Readme in Hindi! I know Hindi Language (Reading and Writing). If you are fine then we can merge it!

2017-03-23 19:20 UTC, auremoser approved these changes
Looks great, I'm sorry I don't read hindi so I can't QA this :/ but it looks great for now! Thank you so much!

2017-03-23 19:20 UTC, auremoser approved these changes
Great, thank you!

2017-03-23 19:21 UTC, auremoser commented on README.md
> -
Would be great to add "Read this in Hindi" as a link here, just like the "read this in Portuguese" link below this line.

2017-03-23 19:21 UTC, auremoser requested changes
If you would add the link to the readme for Hindi here, that would be lovely. Thank you!

2017-03-24 04:44 UTC, AnamikaD commented
@auremoser surely will add that :)

2017-03-24 13:22 UTC, auremoser approved these changes
Excellent, thank you!!

2017-03-24 13:22 UTC, merged

2017-03-29 01:58 UTC, elionaimc commented
Great job done with hindi language and updating the general readme.md file.
Two questions:
a) Dont think that is better delete the file finishing with ~ character? (it seems like used to be a temporary file)
b) With last update in the general readme.md file, it looks very diferent of the portuguese version, do you people think it is ok leave as is or change it to make a real translation of the new english version?

2017-03-29 15:09 UTC, auremoser commented
Hey @elionaimc ! 
@AnamikaD did the translation 🎊  to her!
> a) Dont think that is better delete the file finishing with ~ character? (it seems like used to be a temporary file)

Yes, usually, what file are you referencing? I try to update the `.gitignore` file with unwanted commit files

> b) With last update in the general readme.md file, it looks very diferent of the portuguese version, do you people think it is ok leave as is or change it to make a real translation of the new english version?

Good point, yes we changed the README in English and never updated the Portuguese equivalent for lack of experience with Portuguese. I'll add it as an issue to update the Portuguese readme.

Thank you for your comments!

2017-03-29 15:22 UTC, auremoser commented
I just removed the hidden file, thanks @elionaimc !

2017-03-29 17:51 UTC, elionaimc commented
Great! 
I will start working with README portuguese translation right now!