Readme updated
mozillascience/studyGroup pull request #75
Opened 2017-03-25 04:59 UTC by AnamikaD

@auremoser  Updated README.md with the information on "how to set up Mozilla Study Group locally". If it looks good, I will update it in README-hi.md!

2017-03-25 15:40 UTC, auremoser requested changes
Thank you, this is great, maybe split all the Terminal commands into the same instruction. Otherwise, thank you so much!!!

2017-03-25 15:40 UTC, auremoser commented on README.md
> +* Open Terminal: git clone of the forked repository.
Maybe split this into two instructions: 
* Open Terminal (on a Mac) or the equivalent on your machine
* Type git clone [SSH OR HTTPS CODE FOR studyGroup]

2017-03-25 16:31 UTC, AnamikaD commented
@auremoser Please review it!

2017-03-28 19:19 UTC, auremoser approved these changes
Excellent updates, thank you!

2017-03-28 19:19 UTC, merged

2017-03-29 03:20 UTC, AnamikaD commented
@auremoser thank you! Let me know for any changes!